/*
 * glfx.js
 * http://evanw.github.com/glfx.js/
 *
 * Copyright 2011 Evan Wallace
 * Released under the MIT license
 */
var fx=function(){function k(a,d,c){return Math.max(a,Math.min(d,c))}function v(a){return{_:a,loadContentsOf:function(a){this._.loadContentsOf(a)},destroy:function(){this._.destroy()}}}function C(a){return v(n.fromElement(a))}function D(b,d,c){if(!this._.isInitialized||b._.width!=this.width||b._.height!=this.height){d=d?d:b._.width;c=c?c:b._.height;var e=a.UNSIGNED_BYTE;if(a.getExtension("OES_texture_float")){var f=new n(100,100,a.RGBA,a.FLOAT);try{f.drawTo(function(){e=a.FLOAT})}catch(p){}f.destroy()}this._.texture&&
this._.texture.destroy();this._.spareTexture&&this._.spareTexture.destroy();this.width=d;this.height=c;this._.texture=new n(d,c,a.RGBA,e);this._.spareTexture=new n(d,c,a.RGBA,e);this._.extraTexture=this._.extraTexture||new n(0,0,a.RGBA,e);this._.flippedShader=this._.flippedShader||new j(null,"uniform sampler2D texture;varying vec2 texCoord;void main(){gl_FragColor=texture2D(texture,vec2(texCoord.x,1.0-texCoord.y));}");this._.isInitialized=!0}b._.use();
this._.texture.drawTo(function(){j.getDefaultShader().drawRect()});return this}function E(){this._.texture.use();this._.flippedShader.drawRect();return this}function h(a,d,c,e){(c||this._.texture).use();this._.spareTexture.drawTo(function(){a.uniforms(d).drawRect()});this._.spareTexture.swapWith(e||this._.texture)}function F(a){a.parentNode.insertBefore(this,a);a.parentNode.removeChild(a);return this}function G(){var b=new n(this._.texture.width,this._.texture.height,a.RGBA,a.UNSIGNED_BYTE);this._.texture.use();
b.drawTo(function(){j.getDefaultShader().drawRect()});return v(b)}function w(){var b=this._.texture.width,d=this._.texture.height,c=new Uint8Array(4*b*d);this._.texture.drawTo(function(){a.readPixels(0,0,b,d,a.RGBA,a.UNSIGNED_BYTE,c)});return c}function H(a){var d=this._.texture.width,c=this._.texture.height,e=w.call(this),f=document.createElement("canvas"),p=f.getContext("2d");f.width=d;f.height=c;d=p.createImageData(d,c);for(c=0;c<e.length;c++)d.data[c]=e[c];p.putImageData(d,0,0);return f.toDataURL(a)}
function g(b){return function(){a=this._.gl;return b.apply(this,arguments)}}function x(a,d,c,e,f,p,j,g){var h=c-f,l=e-p,k=j-f,m=g-p;f=a-c+f-j;p=d-e+p-g;var n=h*m-k*l,k=(f*m-k*p)/n,h=(h*p-f*l)/n;return[c-a+k*c,e-d+k*e,k,j-a+h*j,g-d+h*g,h,a,d,1]}function y(a){var d=a[0],c=a[1],e=a[2],f=a[3],h=a[4],j=a[5],g=a[6],k=a[7];a=a[8];var l=d*h*a-d*j*k-c*f*a+c*j*g+e*f*k-e*h*g;return[(h*a-j*k)/l,(e*k-c*a)/l,(c*j-e*h)/l,(j*g-f*a)/l,(d*a-e*g)/l,(e*f-d*j)/l,(f*k-h*g)/l,(c*g-d*k)/l,(d*h-c*f)/l]}function z(a){var d=
a.length;this.xa=[];this.ya=[];this.u=[];this.y2=[];a.sort(function(a,b){return a[0]-b[0]});for(var c=0;c<d;c++)this.xa.push(a[c][0]),this.ya.push(a[c][1]);this.u[0]=0;this.y2[0]=0;for(c=1;c<d-1;++c){a=this.xa[c+1]-this.xa[c-1];var e=(this.xa[c]-this.xa[c-1])/a,f=e*this.y2[c-1]+2;this.y2[c]=(e-1)/f;this.u[c]=(6*((this.ya[c+1]-this.ya[c])/(this.xa[c+1]-this.xa[c])-(this.ya[c]-this.ya[c-1])/(this.xa[c]-this.xa[c-1]))/a-e*this.u[c-1])/f}this.y2[d-1]=0;for(c=d-2;0<=c;--c)this.y2[c]=this.y2[c]*this.y2[c+
1]+this.u[c]}function t(a,d){return new j(null,a+"uniform sampler2D texture;uniform vec2 texSize;varying vec2 texCoord;void main(){vec2 coord=texCoord*texSize;"+d+"gl_FragColor=texture2D(texture,coord/texSize);vec2 clampedCoord=clamp(coord,vec2(0.0),texSize);if(coord!=clampedCoord){gl_FragColor.a*=max(0.0,1.0-length(coord-clampedCoord));}}")}
function I(b,d){a.brightnessContrast=a.brightnessContrast||new j(null,"uniform sampler2D texture;uniform float brightness;uniform float contrast;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.rgb+=brightness;if(contrast>0.0){color.rgb=(color.rgb-0.5)/(1.0-contrast)+0.5;}else{color.rgb=(color.rgb-0.5)*(1.0+contrast)+0.5;}gl_FragColor=color;}");
h.call(this,a.brightnessContrast,{brightness:k(-1,b,1),contrast:k(-1,d,1)});return this}function s(a){a=new z(a);for(var d=[],c=0;256>c;c++)d.push(k(0,Math.floor(256*a.interpolate(c/255)),255));return d}function J(b,d,c){b=s(b);1==arguments.length?d=c=b:(d=s(d),c=s(c));for(var e=[],f=0;256>f;f++)e.splice(e.length,0,b[f],d[f],c[f],255);this._.extraTexture.initFromBytes(256,1,e);this._.extraTexture.use(1);a.curves=a.curves||new j(null,"uniform sampler2D texture;uniform sampler2D map;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.r=texture2D(map,vec2(color.r)).r;color.g=texture2D(map,vec2(color.g)).g;color.b=texture2D(map,vec2(color.b)).b;gl_FragColor=color;}");
a.curves.textures({map:1});h.call(this,a.curves,{});return this}function K(b){a.denoise=a.denoise||new j(null,"uniform sampler2D texture;uniform float exponent;uniform float strength;uniform vec2 texSize;varying vec2 texCoord;void main(){vec4 center=texture2D(texture,texCoord);vec4 color=vec4(0.0);float total=0.0;for(float x=-4.0;x<=4.0;x+=1.0){for(float y=-4.0;y<=4.0;y+=1.0){vec4 sample=texture2D(texture,texCoord+vec2(x,y)/texSize);float weight=1.0-abs(dot(sample.rgb-center.rgb,vec3(0.25)));weight=pow(weight,exponent);color+=sample*weight;total+=weight;}}gl_FragColor=color/total;}");
for(var d=0;2>d;d++)h.call(this,a.denoise,{exponent:Math.max(0,b),texSize:[this.width,this.height]});return this}function L(b,d){a.hueSaturation=a.hueSaturation||new j(null,"uniform sampler2D texture;uniform float hue;uniform float saturation;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float angle=hue*3.14159265;float s=sin(angle),c=cos(angle);vec3 weights=(vec3(2.0*c,-sqrt(3.0)*s-c,sqrt(3.0)*s-c)+1.0)/3.0;float len=length(color.rgb);color.rgb=vec3(dot(color.rgb,weights.xyz),dot(color.rgb,weights.zxy),dot(color.rgb,weights.yzx));float average=(color.r+color.g+color.b)/3.0;if(saturation>0.0){color.rgb+=(average-color.rgb)*(1.0-1.0/(1.001-saturation));}else{color.rgb+=(average-color.rgb)*(-saturation);}gl_FragColor=color;}");
h.call(this,a.hueSaturation,{hue:k(-1,b,1),saturation:k(-1,d,1)});return this}function M(b){a.noise=a.noise||new j(null,"uniform sampler2D texture;uniform float amount;varying vec2 texCoord;float rand(vec2 co){return fract(sin(dot(co.xy,vec2(12.9898,78.233)))*43758.5453);}void main(){vec4 color=texture2D(texture,texCoord);float diff=(rand(texCoord)-0.5)*amount;color.r+=diff;color.g+=diff;color.b+=diff;gl_FragColor=color;}");
h.call(this,a.noise,{amount:k(0,b,1)});return this}function N(b){a.sepia=a.sepia||new j(null,"uniform sampler2D texture;uniform float amount;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float r=color.r;float g=color.g;float b=color.b;color.r=min(1.0,(r*(1.0-(0.607*amount)))+(g*(0.769*amount))+(b*(0.189*amount)));color.g=min(1.0,(r*0.349*amount)+(g*(1.0-(0.314*amount)))+(b*0.168*amount));color.b=min(1.0,(r*0.272*amount)+(g*0.534*amount)+(b*(1.0-(0.869*amount))));gl_FragColor=color;}");
h.call(this,a.sepia,{amount:k(0,b,1)});return this}function O(b,d){a.unsharpMask=a.unsharpMask||new j(null,"uniform sampler2D blurredTexture;uniform sampler2D originalTexture;uniform float strength;uniform float threshold;varying vec2 texCoord;void main(){vec4 blurred=texture2D(blurredTexture,texCoord);vec4 original=texture2D(originalTexture,texCoord);gl_FragColor=mix(blurred,original,1.0+strength);}");
this._.extraTexture.ensureFormat(this._.texture);this._.texture.use();this._.extraTexture.drawTo(function(){j.getDefaultShader().drawRect()});this._.extraTexture.use(1);this.triangleBlur(b);a.unsharpMask.textures({originalTexture:1});h.call(this,a.unsharpMask,{strength:d});this._.extraTexture.unuse(1);return this}function P(b){a.vibrance=a.vibrance||new j(null,"uniform sampler2D texture;uniform float amount;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float average=(color.r+color.g+color.b)/3.0;float mx=max(color.r,max(color.g,color.b));float amt=(mx-average)*(-amount*3.0);color.rgb=mix(color.rgb,vec3(mx),amt);gl_FragColor=color;}");
h.call(this,a.vibrance,{amount:k(-1,b,1)});return this}function Q(b,d){a.vignette=a.vignette||new j(null,"uniform sampler2D texture;uniform float size;uniform float amount;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float dist=distance(texCoord,vec2(0.5,0.5));color.rgb*=smoothstep(0.8,size*0.799,dist*(amount+size));gl_FragColor=color;}");
h.call(this,a.vignette,{size:k(0,b,1),amount:k(0,d,1)});return this}function R(b,d,c){a.lensBlurPrePass=a.lensBlurPrePass||new j(null,"uniform sampler2D texture;uniform float power;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color=pow(color,vec4(power));gl_FragColor=vec4(color);}");var e="uniform sampler2D texture0;uniform sampler2D texture1;uniform vec2 delta0;uniform vec2 delta1;uniform float power;varying vec2 texCoord;"+
r+"vec4 sample(vec2 delta){float offset=random(vec3(delta,151.7182),0.0);vec4 color=vec4(0.0);float total=0.0;for(float t=0.0;t<=30.0;t++){float percent=(t+offset)/30.0;color+=texture2D(texture0,texCoord+delta*percent);total+=1.0;}return color/total;}";
a.lensBlur0=a.lensBlur0||new j(null,e+"void main(){gl_FragColor=sample(delta0);}");a.lensBlur1=a.lensBlur1||new j(null,e+"void main(){gl_FragColor=(sample(delta0)+sample(delta1))*0.5;}");a.lensBlur2=a.lensBlur2||(new j(null,e+"void main(){vec4 color=(sample(delta0)+2.0*texture2D(texture1,texCoord))/3.0;gl_FragColor=pow(color,vec4(power));}")).textures({texture1:1});for(var e=
[],f=0;3>f;f++){var g=c+2*f*Math.PI/3;e.push([b*Math.sin(g)/this.width,b*Math.cos(g)/this.height])}b=Math.pow(10,k(-1,d,1));h.call(this,a.lensBlurPrePass,{power:b});this._.extraTexture.ensureFormat(this._.texture);h.call(this,a.lensBlur0,{delta0:e[0]},this._.texture,this._.extraTexture);h.call(this,a.lensBlur1,{delta0:e[1],delta1:e[2]},this._.extraTexture,this._.extraTexture);h.call(this,a.lensBlur0,{delta0:e[1]});this._.extraTexture.use(1);h.call(this,a.lensBlur2,{power:1/b,delta0:e[2]});return this}
function S(b,d,c,e,f,g){a.tiltShift=a.tiltShift||new j(null,"uniform sampler2D texture;uniform float blurRadius;uniform float gradientRadius;uniform vec2 start;uniform vec2 end;uniform vec2 delta;uniform vec2 texSize;varying vec2 texCoord;"+r+"void main(){vec4 color=vec4(0.0);float total=0.0;float offset=random(vec3(12.9898,78.233,151.7182),0.0);vec2 normal=normalize(vec2(start.y-end.y,end.x-start.x));float radius=smoothstep(0.0,1.0,abs(dot(texCoord*texSize-start,normal))/gradientRadius)*blurRadius;for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec4 sample=texture2D(texture,texCoord+delta/texSize*percent*radius);sample.rgb*=sample.a;color+=sample*weight;total+=weight;}gl_FragColor=color/total;gl_FragColor.rgb/=gl_FragColor.a+0.00001;}");
var k=c-b,l=e-d,m=Math.sqrt(k*k+l*l);h.call(this,a.tiltShift,{blurRadius:f,gradientRadius:g,start:[b,d],end:[c,e],delta:[k/m,l/m],texSize:[this.width,this.height]});h.call(this,a.tiltShift,{blurRadius:f,gradientRadius:g,start:[b,d],end:[c,e],delta:[-l/m,k/m],texSize:[this.width,this.height]});return this}function T(b){a.triangleBlur=a.triangleBlur||new j(null,"uniform sampler2D texture;uniform vec2 delta;varying vec2 texCoord;"+r+"void main(){vec4 color=vec4(0.0);float total=0.0;float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec4 sample=texture2D(texture,texCoord+delta*percent);sample.rgb*=sample.a;color+=sample*weight;total+=weight;}gl_FragColor=color/total;gl_FragColor.rgb/=gl_FragColor.a+0.00001;}");
h.call(this,a.triangleBlur,{delta:[b/this.width,0]});h.call(this,a.triangleBlur,{delta:[0,b/this.height]});return this}function U(b,d,c){a.zoomBlur=a.zoomBlur||new j(null,"uniform sampler2D texture;uniform vec2 center;uniform float strength;uniform vec2 texSize;varying vec2 texCoord;"+r+"void main(){vec4 color=vec4(0.0);float total=0.0;vec2 toCenter=center-texCoord*texSize;float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=0.0;t<=40.0;t++){float percent=(t+offset)/40.0;float weight=4.0*(percent-percent*percent);vec4 sample=texture2D(texture,texCoord+toCenter*percent*strength/texSize);sample.rgb*=sample.a;color+=sample*weight;total+=weight;}gl_FragColor=color/total;gl_FragColor.rgb/=gl_FragColor.a+0.00001;}");
h.call(this,a.zoomBlur,{center:[b,d],strength:c,texSize:[this.width,this.height]});return this}function V(b,d,c,e){a.colorHalftone=a.colorHalftone||new j(null,"uniform sampler2D texture;uniform vec2 center;uniform float angle;uniform float scale;uniform vec2 texSize;varying vec2 texCoord;float pattern(float angle){float s=sin(angle),c=cos(angle);vec2 tex=texCoord*texSize-center;vec2 point=vec2(c*tex.x-s*tex.y,s*tex.x+c*tex.y)*scale;return(sin(point.x)*sin(point.y))*4.0;}void main(){vec4 color=texture2D(texture,texCoord);vec3 cmy=1.0-color.rgb;float k=min(cmy.x,min(cmy.y,cmy.z));cmy=(cmy-k)/(1.0-k);cmy=clamp(cmy*10.0-3.0+vec3(pattern(angle+0.26179),pattern(angle+1.30899),pattern(angle)),0.0,1.0);k=clamp(k*10.0-5.0+pattern(angle+0.78539),0.0,1.0);gl_FragColor=vec4(1.0-cmy-k,color.a);}");
h.call(this,a.colorHalftone,{center:[b,d],angle:c,scale:Math.PI/e,texSize:[this.width,this.height]});return this}function W(b,d,c,e){a.dotScreen=a.dotScreen||new j(null,"uniform sampler2D texture;uniform vec2 center;uniform float angle;uniform float scale;uniform vec2 texSize;varying vec2 texCoord;float pattern(){float s=sin(angle),c=cos(angle);vec2 tex=texCoord*texSize-center;vec2 point=vec2(c*tex.x-s*tex.y,s*tex.x+c*tex.y)*scale;return(sin(point.x)*sin(point.y))*4.0;}void main(){vec4 color=texture2D(texture,texCoord);float average=(color.r+color.g+color.b)/3.0;gl_FragColor=vec4(vec3(average*10.0-5.0+pattern()),color.a);}");
h.call(this,a.dotScreen,{center:[b,d],angle:c,scale:Math.PI/e,texSize:[this.width,this.height]});return this}function X(b){a.edgeWork1=a.edgeWork1||new j(null,"uniform sampler2D texture;uniform vec2 delta;varying vec2 texCoord;"+r+"void main(){vec2 color=vec2(0.0);vec2 total=vec2(0.0);float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec3 sample=texture2D(texture,texCoord+delta*percent).rgb;float average=(sample.r+sample.g+sample.b)/3.0;color.x+=average*weight;total.x+=weight;if(abs(t)<15.0){weight=weight*2.0-1.0;color.y+=average*weight;total.y+=weight;}}gl_FragColor=vec4(color/total,0.0,1.0);}");
a.edgeWork2=a.edgeWork2||new j(null,"uniform sampler2D texture;uniform vec2 delta;varying vec2 texCoord;"+r+"void main(){vec2 color=vec2(0.0);vec2 total=vec2(0.0);float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec2 sample=texture2D(texture,texCoord+delta*percent).xy;color.x+=sample.x*weight;total.x+=weight;if(abs(t)<15.0){weight=weight*2.0-1.0;color.y+=sample.y*weight;total.y+=weight;}}float c=clamp(10000.0*(color.y/total.y-color.x/total.x)+0.5,0.0,1.0);gl_FragColor=vec4(c,c,c,1.0);}");
h.call(this,a.edgeWork1,{delta:[b/this.width,0]});h.call(this,a.edgeWork2,{delta:[0,b/this.height]});return this}function Y(b,d,c){a.hexagonalPixelate=a.hexagonalPixelate||new j(null,"uniform sampler2D texture;uniform vec2 center;uniform float scale;uniform vec2 texSize;varying vec2 texCoord;void main(){vec2 tex=(texCoord*texSize-center)/scale;tex.y/=0.866025404;tex.x-=tex.y*0.5;vec2 a;if(tex.x+tex.y-floor(tex.x)-floor(tex.y)<1.0)a=vec2(floor(tex.x),floor(tex.y));else a=vec2(ceil(tex.x),ceil(tex.y));vec2 b=vec2(ceil(tex.x),floor(tex.y));vec2 c=vec2(floor(tex.x),ceil(tex.y));vec3 TEX=vec3(tex.x,tex.y,1.0-tex.x-tex.y);vec3 A=vec3(a.x,a.y,1.0-a.x-a.y);vec3 B=vec3(b.x,b.y,1.0-b.x-b.y);vec3 C=vec3(c.x,c.y,1.0-c.x-c.y);float alen=length(TEX-A);float blen=length(TEX-B);float clen=length(TEX-C);vec2 choice;if(alen<blen){if(alen<clen)choice=a;else choice=c;}else{if(blen<clen)choice=b;else choice=c;}choice.x+=choice.y*0.5;choice.y*=0.866025404;choice*=scale/texSize;gl_FragColor=texture2D(texture,choice+center/texSize);}");
h.call(this,a.hexagonalPixelate,{center:[b,d],scale:c,texSize:[this.width,this.height]});return this}function Z(b){a.ink=a.ink||new j(null,"uniform sampler2D texture;uniform float strength;uniform vec2 texSize;varying vec2 texCoord;void main(){vec2 dx=vec2(1.0/texSize.x,0.0);vec2 dy=vec2(0.0,1.0/texSize.y);vec4 color=texture2D(texture,texCoord);float bigTotal=0.0;float smallTotal=0.0;vec3 bigAverage=vec3(0.0);vec3 smallAverage=vec3(0.0);for(float x=-2.0;x<=2.0;x+=1.0){for(float y=-2.0;y<=2.0;y+=1.0){vec3 sample=texture2D(texture,texCoord+dx*x+dy*y).rgb;bigAverage+=sample;bigTotal+=1.0;if(abs(x)+abs(y)<2.0){smallAverage+=sample;smallTotal+=1.0;}}}vec3 edge=max(vec3(0.0),bigAverage/bigTotal-smallAverage/smallTotal);gl_FragColor=vec4(color.rgb-dot(edge,edge)*strength*100000.0,color.a);}");
h.call(this,a.ink,{strength:b*b*b*b*b,texSize:[this.width,this.height]});return this}function $(b,d,c,e){a.bulgePinch=a.bulgePinch||t("uniform float radius;uniform float strength;uniform vec2 center;","coord-=center;float distance=length(coord);if(distance<radius){float percent=distance/radius;if(strength>0.0){coord*=mix(1.0,smoothstep(0.0,radius/distance,percent),strength*0.75);}else{coord*=mix(1.0,pow(percent,1.0+strength*0.75)*radius/distance,1.0-percent);}}coord+=center;");
h.call(this,a.bulgePinch,{radius:c,strength:k(-1,e,1),center:[b,d],texSize:[this.width,this.height]});return this}function aa(b,d,c){a.matrixWarp=a.matrixWarp||t("uniform mat3 matrix;uniform bool useTextureSpace;","if(useTextureSpace)coord=coord/texSize*2.0-1.0;vec3 warp=matrix*vec3(coord,1.0);coord=warp.xy/warp.z;if(useTextureSpace)coord=(coord*0.5+0.5)*texSize;");b=Array.prototype.concat.apply([],b);if(4==b.length)b=
[b[0],b[1],0,b[2],b[3],0,0,0,1];else if(9!=b.length)throw"can only warp with 2x2 or 3x3 matrix";h.call(this,a.matrixWarp,{matrix:d?y(b):b,texSize:[this.width,this.height],useTextureSpace:c|0});return this}function ba(a,d){var c=x.apply(null,d),e=x.apply(null,a),c=y(c);return this.matrixWarp([c[0]*e[0]+c[1]*e[3]+c[2]*e[6],c[0]*e[1]+c[1]*e[4]+c[2]*e[7],c[0]*e[2]+c[1]*e[5]+c[2]*e[8],c[3]*e[0]+c[4]*e[3]+c[5]*e[6],c[3]*e[1]+c[4]*e[4]+c[5]*e[7],c[3]*e[2]+c[4]*e[5]+c[5]*e[8],c[6]*e[0]+c[7]*e[3]+c[8]*e[6],
c[6]*e[1]+c[7]*e[4]+c[8]*e[7],c[6]*e[2]+c[7]*e[5]+c[8]*e[8]])}function ca(b,d,c,e){a.swirl=a.swirl||t("uniform float radius;uniform float angle;uniform vec2 center;","coord-=center;float distance=length(coord);if(distance<radius){float percent=(radius-distance)/radius;float theta=percent*percent*angle;float s=sin(theta);float c=cos(theta);coord=vec2(coord.x*c-coord.y*s,coord.x*s+coord.y*c);}coord+=center;");
h.call(this,a.swirl,{radius:c,center:[b,d],angle:e,texSize:[this.width,this.height]});return this}var u={},a;u.canvas=function(){var b=document.createElement("canvas");try{a=b.getContext("experimental-webgl",{premultipliedAlpha:!1})}catch(d){a=null}if(!a)throw"This browser does not support WebGL";b._={gl:a,isInitialized:!1,texture:null,spareTexture:null,flippedShader:null};b.texture=g(C);b.draw=g(D);b.update=g(E);b.replace=g(F);b.contents=g(G);b.getPixelArray=g(w);b.toDataURL=g(H);b.brightnessContrast=
g(I);b.hexagonalPixelate=g(Y);b.hueSaturation=g(L);b.colorHalftone=g(V);b.triangleBlur=g(T);b.unsharpMask=g(O);b.perspective=g(ba);b.matrixWarp=g(aa);b.bulgePinch=g($);b.tiltShift=g(S);b.dotScreen=g(W);b.edgeWork=g(X);b.lensBlur=g(R);b.zoomBlur=g(U);b.noise=g(M);b.denoise=g(K);b.curves=g(J);b.swirl=g(ca);b.ink=g(Z);b.vignette=g(Q);b.vibrance=g(P);b.sepia=g(N);return b};u.splineInterpolate=s;var j,A=function(b,d){var c=a.createShader(b);a.shaderSource(c,d);a.compileShader(c);if(!a.getShaderParameter(c,
a.COMPILE_STATUS))throw"compile error: "+a.getShaderInfoLog(c);return c},q=function(b,d){this.texCoordAttribute=this.vertexAttribute=null;this.program=a.createProgram();b=b||da;d=d||ea;d="precision highp float;"+d;a.attachShader(this.program,A(a.VERTEX_SHADER,b));a.attachShader(this.program,A(a.FRAGMENT_SHADER,d));a.linkProgram(this.program);if(!a.getProgramParameter(this.program,a.LINK_STATUS))throw"link error: "+a.getProgramInfoLog(this.program);},da="attribute vec2 vertex;attribute vec2 _texCoord;varying vec2 texCoord;void main(){texCoord=_texCoord;gl_Position=vec4(vertex*2.0-1.0,0.0,1.0);}",
ea="uniform sampler2D texture;varying vec2 texCoord;void main(){gl_FragColor=texture2D(texture,texCoord);}";q.prototype.destroy=function(){a.deleteProgram(this.program);this.program=null};q.prototype.uniforms=function(b){a.useProgram(this.program);for(var d in b)if(b.hasOwnProperty(d)){var c=a.getUniformLocation(this.program,d);if(null!==c){var e=b[d];if("[object Array]"==Object.prototype.toString.call(e))switch(e.length){case 1:a.uniform1fv(c,new Float32Array(e));break;
case 2:a.uniform2fv(c,new Float32Array(e));break;case 3:a.uniform3fv(c,new Float32Array(e));break;case 4:a.uniform4fv(c,new Float32Array(e));break;case 9:a.uniformMatrix3fv(c,!1,new Float32Array(e));break;case 16:a.uniformMatrix4fv(c,!1,new Float32Array(e));break;default:throw"dont't know how to load uniform \""+d+'" of length '+e.length;}else if("[object Number]"==Object.prototype.toString.call(e))a.uniform1f(c,e);else throw'attempted to set uniform "'+d+'" to invalid value '+(e||"undefined").toString();
}}return this};q.prototype.textures=function(b){a.useProgram(this.program);for(var d in b)b.hasOwnProperty(d)&&a.uniform1i(a.getUniformLocation(this.program,d),b[d]);return this};q.prototype.drawRect=function(b,d,c,e){var f=a.getParameter(a.VIEWPORT);d=void 0!==d?(d-f[1])/f[3]:0;b=void 0!==b?(b-f[0])/f[2]:0;c=void 0!==c?(c-f[0])/f[2]:1;e=void 0!==e?(e-f[1])/f[3]:1;null==a.vertexBuffer&&(a.vertexBuffer=a.createBuffer());a.bindBuffer(a.ARRAY_BUFFER,a.vertexBuffer);a.bufferData(a.ARRAY_BUFFER,new Float32Array([b,
d,b,e,c,d,c,e]),a.STATIC_DRAW);null==a.texCoordBuffer&&(a.texCoordBuffer=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,a.texCoordBuffer),a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,0,1,1]),a.STATIC_DRAW));null==this.vertexAttribute&&(this.vertexAttribute=a.getAttribLocation(this.program,"vertex"),a.enableVertexAttribArray(this.vertexAttribute));null==this.texCoordAttribute&&(this.texCoordAttribute=a.getAttribLocation(this.program,"_texCoord"),a.enableVertexAttribArray(this.texCoordAttribute));
a.useProgram(this.program);a.bindBuffer(a.ARRAY_BUFFER,a.vertexBuffer);a.vertexAttribPointer(this.vertexAttribute,2,a.FLOAT,!1,0,0);a.bindBuffer(a.ARRAY_BUFFER,a.texCoordBuffer);a.vertexAttribPointer(this.texCoordAttribute,2,a.FLOAT,!1,0,0);a.drawArrays(a.TRIANGLE_STRIP,0,4)};q.getDefaultShader=function(){a.defaultShader=a.defaultShader||new q;return a.defaultShader};j=q;z.prototype.interpolate=function(a){for(var d=0,c=this.ya.length-1;1<c-d;){var e=c+d>>1;this.xa[e]>a?c=e:d=e}var e=this.xa[c]-this.xa[d],
f=(this.xa[c]-a)/e;a=(a-this.xa[d])/e;return f*this.ya[d]+a*this.ya[c]+((f*f*f-f)*this.y2[d]+(a*a*a-a)*this.y2[c])*e*e/6};var n,l=function(b,d,c,e){this.id=a.createTexture();this.width=b;this.height=d;this.format=c;this.type=e;a.bindTexture(a.TEXTURE_2D,this.id);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);
b&&d&&a.texImage2D(a.TEXTURE_2D,0,this.format,b,d,0,this.format,this.type,null)},B=function(a){null==m&&(m=document.createElement("canvas"));m.width=a.width;m.height=a.height;a=m.getContext("2d");a.clearRect(0,0,m.width,m.height);return a};l.fromElement=function(b){var d=new l(0,0,a.RGBA,a.UNSIGNED_BYTE);d.loadContentsOf(b);return d};l.prototype.loadContentsOf=function(b){this.width=b.width||b.videoWidth;this.height=b.height||b.videoHeight;a.bindTexture(a.TEXTURE_2D,this.id);a.texImage2D(a.TEXTURE_2D,
0,this.format,this.format,this.type,b)};l.prototype.initFromBytes=function(b,d,c){this.width=b;this.height=d;this.format=a.RGBA;this.type=a.UNSIGNED_BYTE;a.bindTexture(a.TEXTURE_2D,this.id);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,b,d,0,a.RGBA,this.type,new Uint8Array(c))};l.prototype.destroy=function(){a.deleteTexture(this.id);this.id=null};l.prototype.use=function(b){a.activeTexture(a.TEXTURE0+(b||0));a.bindTexture(a.TEXTURE_2D,this.id)};l.prototype.unuse=function(b){a.activeTexture(a.TEXTURE0+(b||0));
a.bindTexture(a.TEXTURE_2D,null)};l.prototype.ensureFormat=function(b,d,c,e){if(1==arguments.length){var f=arguments[0];b=f.width;d=f.height;c=f.format;e=f.type}if(b!=this.width||d!=this.height||c!=this.format||e!=this.type)this.width=b,this.height=d,this.format=c,this.type=e,a.bindTexture(a.TEXTURE_2D,this.id),a.texImage2D(a.TEXTURE_2D,0,this.format,b,d,0,this.format,this.type,null)};l.prototype.drawTo=function(b){a.framebuffer=a.framebuffer||a.createFramebuffer();a.bindFramebuffer(a.FRAMEBUFFER,
a.framebuffer);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,this.id,0);if(a.checkFramebufferStatus(a.FRAMEBUFFER)!==a.FRAMEBUFFER_COMPLETE)throw Error("incomplete framebuffer");a.viewport(0,0,this.width,this.height);b();a.bindFramebuffer(a.FRAMEBUFFER,null)};var m=null;l.prototype.fillUsingCanvas=function(b){b(B(this));this.format=a.RGBA;this.type=a.UNSIGNED_BYTE;a.bindTexture(a.TEXTURE_2D,this.id);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,m);return this};
l.prototype.toImage=function(b){this.use();j.getDefaultShader().drawRect();var d=4*this.width*this.height,c=new Uint8Array(d),e=B(this),f=e.createImageData(this.width,this.height);a.readPixels(0,0,this.width,this.height,a.RGBA,a.UNSIGNED_BYTE,c);for(var g=0;g<d;g++)f.data[g]=c[g];e.putImageData(f,0,0);b.src=m.toDataURL()};l.prototype.swapWith=function(a){var d;d=a.id;a.id=this.id;this.id=d;d=a.width;a.width=this.width;this.width=d;d=a.height;a.height=this.height;this.height=d;d=a.format;a.format=
this.format;this.format=d};n=l;var r="float random(vec3 scale,float seed){return fract(sin(dot(gl_FragCoord.xyz+seed,scale))*43758.5453+seed);}";return u}();
